-- Sample Bridge View DDL
-- Generated by UC Steward reconciliation planner for naming violation
-- Plan ID: a1b2c3d4-e5f6-7890-abcd-ef1234567890

-- Context: Table "prod.analytics.UserSessions" violates snake_case naming convention.
-- UC Steward renamed it to "prod.analytics.user_sessions" and created this bridge view
-- so existing consumers (5 downstream: dashboards, notebooks, pipelines) keep working.

CREATE OR REPLACE VIEW prod.analytics.UserSessions AS
SELECT * FROM prod.analytics.user_sessions;
-- Bridge view expires: 2026-09-29 (90 days — elevated TTL due to dashboard dependency)
-- After expiry, UC Steward will notify remaining consumers and propose DROP VIEW.

-- Registered in control table:
-- INSERT INTO uc_hygiene.bridge_views VALUES (
--   'a1b2c3d4-e5f6-7890-abcd-ef1234567890',  -- plan_id
--   'prod', 'analytics', 'UserSessions',       -- old location (now the view)
--   'prod', 'analytics', 'user_sessions',       -- new location (the real table)
--   DATE'2026-07-01',                           -- created_date
--   DATE'2026-09-29',                           -- expiry_date
--   5,                                          -- downstream_count at creation
--   'active'                                    -- status
-- );
